version: '3.9'
services:
  
  db:
    image: "postgres"
    ports:  ["5434:5432"]
    environment: 

        "POSTGRES_PASSWORD": "root"
        "POSTGRES_USER": "postgres"
        "POSTGRES_DB":  "Capson"

  server:
    build: .
    ports:  ["4000:4000"]
    depends_on:
      - db
    